FROM php:7.3.6-fpm-alpine3.9

#RUN pecl install swoole \ 
#&& docker-php-ext-enable swoole
#Copyr the file in project called 9501 to the path inside the image
#COPY index.php /var/www
#EXPOSE the port 9501 to 9501 in docker

#Set the initial path to the path inside workdir, inside container
WORKDIR /var/www
#Remover volder html from container
RUN rm -rf /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#COPY . /var/wwww

#RUN composer install

#COPY all files of the path

#Link folder public of laravel with folder html inside container
RUN ln -s public html

EXPOSE 9000
#Comands when container starts
ENTRYPOINT ["php-fpm"]